# Generated by Django 4.0.4 on 2022-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='A', max_length=1)),
                ('target', models.CharField(default='B', max_length=1)),
                ('distance', models.IntegerField(default=6)),
            ],
        ),
    ]
