# Generated by Django 4.0.4 on 2022-04-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_transporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='source',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='target',
        ),
        migrations.AddField(
            model_name='graph',
            name='routeQuantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='A', max_length=1)),
                ('target', models.CharField(default='B', max_length=1)),
                ('distance', models.IntegerField(default=6)),
                ('graphId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_transporte.graph')),
            ],
        ),
    ]
