# Generated by Django 4.0.4 on 2022-04-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_transporte', '0002_remove_graph_distance_remove_graph_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='routeQuantity',
            new_name='numberOfRoutes',
        ),
    ]
